name = "Vertical Land"
license = "MIT"
licenselink = "https://github.com/lp1dev/vertical-land/blob/master/LICENSE.md"
description = "Vertical Simple and Clean Landing Page"
homepage = "https://lp1.eu"
tags = ["landing page", "clean", "boilerplate"]
features = []
min_version = "0.27.1"

[author]
  name = "Jérémie Amsellem"
  homepage = "https://lp1.eu"
